# Generated by Django 4.0.2 on 2022-02-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=300)),
                ('age', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'owners',
            },
        ),
        migrations.RemoveField(
            model_name='allergy_drink',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='allergy_drink',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='category',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='size',
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='allergy_drink',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.owner'),
        ),
    ]
